### ISSUE TITLE
[kde5port]can't find gpgme

### ISSUE THREAD

**Issue by marguerite** [basket-notepads/basket#20]
<pre>
[  202s]   By not providing "FindGpgme.cmake" in CMAKE_MODULE_PATH this project has
[  202s]   asked CMake to find a package configuration file provided by "Gpgme", but
[  202s]   CMake did not find one.
[  202s] 
[  202s]   Could not find a package configuration file provided by "Gpgme" with any of
[  202s]   the following names:
[  202s] 
[  202s]     GpgmeConfig.cmake
[  202s]     gpgme-config.cmake
[  202s] 
[  202s]   Add the installation prefix of "Gpgme" to CMAKE_PREFIX_PATH or set
[  202s]   "Gpgme_DIR" to a directory containing one of the above files.  If "Gpgme"
[  202s]   provides a separate development package or SDK, be sure it has been
[  202s]   installed.
</pre>

I have tried libgpgme-devel and gpgmepp5-devel...but none of them provides GpgmeConfig.cmake or gpgme-config.cmake.

Can you please share the package name on your distribution, or tell me the exact include file basket needs, so that I can add gpgme support to openSUSE?

Thanks

**Comment by gl-bars** [comment]
For me it came with KDE4 version of kdepimlibs-dev. But it should be [KF5GpgmeppConfig.cmake](http://comments.gmane.org/gmane.comp.kde.devel.pim/49201) now (search packages by this filename - should be something like kf5gpgmepp-dev).

Please try this temporary fix:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 0d78080..dcc11ad 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -9,10 +9,6 @@ find_package(X11 REQUIRED)
 find_package(ECM REQUIRED NO_MODULE)
 set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${ECM_MODULE_PATH})
 
-IF(NOT BASKET_DISABLE_GPG)
-  find_package(Gpgme)
-ENDIF(NOT BASKET_DISABLE_GPG)
-
 # libgit2
 set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/cmake/Modules/")
 find_package(Libgit2)
@@ -70,6 +66,10 @@ find_package(Phonon4Qt5 REQUIRED)
 #find_package(KF5 COMPONENTS Baloo)
 
 
+IF(NOT BASKET_DISABLE_GPG)
+  find_package(KF5 COMPONENTS Gpgmepp)
+ENDIF(NOT BASKET_DISABLE_GPG)
+
 IF(GPGME_FOUND)
   SET(HAVE_LIBGPGME 1)
   SET(LARGEFILE_SOURCE_1)
```

I'll commit a fix after I test it.

Thanks

**Comment by marguerite** [comment]
<pre>
[  274s] -- The following OPTIONAL packages have been found:
[  274s] 
[  274s]  * PkgConfig
[  274s]  * Libgit2
[  274s]  * KF5Gpgmepp
</pre>

the patch works!

**Comment by gl-bars** [comment]
Sorry, it was a mistake. Basket still needs plain gpgme library and not any flavor of gpgmepp. Since there is no official FindGpgme.cmake, I'm adding a local copy of it (taken from kdepim).
