### ISSUE TITLE
problem selecting and pasting text with the middle mouse button

### ISSUE THREAD

**Issue by highflyer77** [basket-notepads/basket#21]
I used to be able to paste text into a note using only my middle mouse button, or to be able to select some note text and paste that into my konsole or another app, when I was using Basket Notepads with kde3. I am no longer able to do this using kde4 and with this github ver. 
The selection/paste seems to be only working within the BasKet Notepads itself.
My selection/paste is working normally everywhere else.
Can someone confirm this behavior.

My basket notepads version now says: Version 2.10-beta , I presume this to be correct?
and my OS version is: Ubuntu 14.04.1 LTS

I'm really glad you guys got this program working again with kde4 and hope to see the work continue.
Thank you

**Comment by gl-bars** [comment]
Yes, this is a known bug (https://bugs.kde.org/show_bug.cgi?id=341120) and the reason is that mouse is handled in custom way in Basket editor. I'll look into it for v2.11 but can't promise it will be fixed in KDE4 version.

**Comment by highflyer77** [comment]
@gl-bars 
Thank you, for taking a look at this.
That bug report seems to be mostly, right on. As far as being "handled in a custom way", I know that it always worked fine before with KDE3. I really miss all the functionallity of it, when it was running on KDE3. It really was the best note taking program that I have ever come across and I look forward to using it extensively again. Thanks to everyone for bringing it back. I have been idling at #basket, Let me know if I can help.

**Comment by highflyer77** [comment]
@gl-bars 
Wow, you made my day! 
Much better now, Thank you!
