### ISSUE TITLE
[kde5] Basket freezes when renaming a file entry

### ISSUE THREAD

**Issue by pauleve** [basket-notepads/basket#31]
With the KDE5 version, when renaming a file entry, Basket become frozen (without any special output in the console or .xsession-errors).

**Comment by gl-bars** [comment]
Can you please write exact actions (step by step) which lead to freeze?

**Comment by pauleve** [comment]
Drag'n drop a file in a basket ; then either click on its icon ; or press enter ; or press right-click > edit.
All cases lead to freeze.

**Comment by gl-bars** [comment]
Thanks, now it should be fixed.
